CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
	Appl_No VARCHAR(50) PRIMARY KEY,
	Ingredient VARCHAR(255) NOT NULL,
	Dosage VARCHAR(50) NOT NULL,
	Form VARCHAR(50) NOT NULL,
	Route VARCHAR(50) NOT NULL,
	Applicant VARCHAR(255) NOT NULL,
	Strength VARCHAR(255) NOT NULL,
	Appl_Type CHAR(1) NOT NULL,
	TE_Code VARCHAR(10),
	Approval_Date DATE NOT NULL,
	RLD BOOLEAN NOT NULL,
	RS BOOLEAN NOT NULL,
	Type VARCHAR(10) NOT NULL, 
	Applicant_Full_Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS patent (
	Appl_No VARCHAR(50) PRIMARY KEY,
	Ingredient VARCHAR(255) NOT NULL,
	Dosage VARCHAR(50),
	FORM VARCHAR(50) NOT NULL,
	ROUTE VARCHAR(50) NOT NULL,
	Applicant VARCHAR(255) NOT NULL,
	Strength VARCHAR(50) NOT NULL,
	Approval_Date DATE NOT NULL,
	Patent_No VARCHAR(50) NOT NULL,
	Patent_Expire_Date DATE NOT NULL,
	Drug_Substance_Flag BOOLEAN,
	Drug_Product_Flag BOOLEAN,
	Patent_Use_Code VARCHAR(10) NOT NULL,
	Submission_Date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS exclusivity (
	Appl_No VARCHAR(50) PRIMARY KEY,
	Ingredient VARCHAR(255) PRIMARY KEY,
	Dosage VARCHAR(50) NOT NULL,
	Form VARCHAR(50) NOT NULL,
	Route VARCHAR(50) NOT NULL,
	Applicant VARCHAR(255) NOT NULL,
	Strength VARCHAR(50) NOT NULL,
	Approval_Date DATE NOT NULL,
	Exclusivity_Code VARCHAR(50) NOT NULL,
	Exclusivity_Date DATE NOT NULL
);