CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
	id SERIAL PRIMARY KEY,
	Appl_No VARCHAR(10) NOT NULL,
	Appl_Type CHAR(1) NOT NULL,
	Ingredient VARCHAR(255) NOT NULL,
	Dosage VARCHAR(50),
	Form VARCHAR(50),
	Route VARCHAR(100) NOT NULL,
	Trade_Name VARCHAR(255) NOT NULL,
	Applicant VARCHAR(50) NOT NULL,
	Strength VARCHAR(255),
	Product_No VARCHAR(2) NOT NULL,
	TE_Code VARCHAR(25),
	Approval_Date DATE NOT NULL,
	RLD BOOLEAN NOT NULL,
	RS BOOLEAN NOT NULL,
	Type VARCHAR(10) NOT NULL, 
	Applicant_Full_Name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS patent (
	id SERIAL PRIMARY KEY,
	Appl_No VARCHAR(10) NOT NULL,
	Appl_Type CHAR(1) NOT NULL,
	Ingredient VARCHAR(255) NOT NULL,
	Dosage VARCHAR(50),
	FORM VARCHAR(50),
	ROUTE VARCHAR(50) NOT NULL,
	Trade_Name VARCHAR(255) NOT NULL,
	Applicant VARCHAR(50) NOT NULL,
	Strength VARCHAR(255),
	Product_No VARCHAR(2) NOT NULL,
	Patent_No VARCHAR(50) NOT NULL,
	Patent_Expire_Date_Text DATE NOT NULL,
	Drug_Substance_Flag BOOLEAN,
	Drug_Product_Flag BOOLEAN,
	Patent_Use_Code VARCHAR(10),
	Submission_Date DATE
);

CREATE TABLE IF NOT EXISTS exclusivity (
	id SERIAL PRIMARY KEY,	
	Appl_No VARCHAR(10) NOT NULL,
	Appl_Type CHAR(1) NOT NULL,
	Ingredient VARCHAR(255) NOT NULL,
	Dosage VARCHAR(50),
	Form VARCHAR(50),
	Route VARCHAR(255) NOT NULL,
	TRADE_NAME VARCHAR(255) NOT NULL,
	Strength VARCHAR(255),
	Product_No VARCHAR(2) NOT NULL,
	Exclusivity_Code VARCHAR(50) NOT NULL,
	Exclusivity_Date DATE NOT NULL
);